containerbuildsystem/osbs-docs

- docs/multiarch.rst
> Describe build.extra.image.index Koji build metadata

- docs/multiarch.rst
It is likely that different platforms will use not only
different package sets but even different n-v-rs of the
same packages -- for instance, the kernel.
As a result, the build system should not prevent this
but merely record the versions used. It will be the job
of sanity-checking/compare-to-previous tools to allow
changes to be reviewed/waived.
> multiarch: remove compare_rpm_packages

- docs/contributors.rst
By including it here, we can simply point to this from within
CONTRIBUTING.md in osbs-client and atomic-reactor.
> Merge atomic-reactor and osbs-client contribution guides

- docs/multiarch.rst
These sections perform two functions:
* set the GOARCH architecture name for each platform, if different from
the platform name
* allow publishing v1 images on a per-platform basis
> Describe new platform:... sections

- docs/multiarch.rst
For the archive 'repositories' list, a by-digest spec is optional
because v2 support is optional. However, for the image.index we
know that v2 support is required in order to have an image index
or manifest list, so a by-digest spec is required in that case.
> image.index.pull must include a by-digest spec

- README.md
- docs/index.rst
Link GitHub users to the main page where readthedocs renders OSBS's documentation so this is easier to find. 
Link the main index page to the koji-containerbuild project so it's easier to find that as well.
~While we're here, koji-containerbuild contains multiple plugins, so pluralize that description.~
> add some project links

- docs/users.rst
Explain how to set "packages" to an empty list in YAML, and explain the trade-off in speed vs complexity for users to decide what they want to do.
> users: more explanation for empty package lists

- docs/build_parameters.rst
- docs/build_process.rst
This fixes the link to the Build Parameters page in https://osbs.readthedocs.io/en/latest/build_process.html#arrangement-version-6-reactor-config-map
> Fix broken link to Build Parameters documentation

- docs/users.rst
> Add documentation for container.yaml's go.module key (OSBS-6492)

- docs/users.rst
#69 was recently merged, introducing outdated information for container-first specs in container.yaml. This updates the docs based on the specs available in `atomic_reactor/schemas/container.json`.
> Update documentation for container.yaml go key

- docs/users.rst
Recommend that developers always have a com.redhat.component label that ends with "-container".
> recommend "-container" suffix for component label

- docs/contributors.rst
All features should have turn off switch in atomic-reactor config file
> Contributors: ensure that new features can be disabled if needed

- docs/users.rst
Describe the `include_unpublished_pulp_repos`: how to use it, and what cautions to exercise.
> describe include_unpublished_pulp_repos setting

- docs/users.rst
as part of osbs-6424, update the docs to include a link to the YAML schema used by fetch maven artifacts.
> fetch maven artifacts: link to YAML schema

- docs/users.rst
Merge the "Configuring koji-containerbuild" section into the main "Building images using koji" section.
Provide the exact `yum install` command, as well as an example of running `--help`.  
This makes it easier for users to understand how to quickly start installing and using this tool.
> users: combine instructions for koji-containerbuild-cli

- docs/build_parameters.rst
- docs/build_process.rst
- docs/reference_docs.rst
part of osbs-5098
Remove all references to pulp and pulp related variables, except
for the pulp references in the historical overview of arrangements.
> remove pulp from the documentation

- docs/reference_docs.rst
This file a .md file (markdown). Update the link to point at the correct location.
> reference: fix link to koji-containerbuild's arch doc

- docs/users.rst
Unfortunately the upstream Kojiweb software does not link container builds back to the corresponding buildContainer tasks.
Here's the ticket that tracks this in Koji upstream: https://pagure.io/koji/issue/215
> users: kojiweb does not (yet) link builds to tasks

- docs/build_process.rst
Delete the duplicate paragraphs, and clarify what we mean by "example below".
> build_process: clarify "example" section reference

- docs/build_parameters.rst
Downward API is an OpenShift mechanism. Link to the OpenShift developer documentation to help users understand this term.
> build_parameters: link downward API

- docs/build_parameters.rst
It's technically true that these settings can change over time, but it's confusing to explicitly suggest that the settings change on a regular basis without going into more detail. Remove this sentence altogether.
> build_parameters: rm description of environment changes

- docs/users.rst
Prior to this change, the content_sets anchor was pointing at the image_build_method section. This caused Sphinx to generate links like "See image_build_method" instead of "See content_sets.yml".
> users: align content_sets.yml anchor with "Content Sets" section

- docs/users.rst
Simplify the language in the "Isolated Builds" section, and add a `fedpkg` example for isolated builds.
> better language and fedpkg example for Isolated Builds

- docs/.aspell.en.pws
- docs/build_parameters.rst
pdc support was deprecated in September 2018, so remove the last remnants
of it from the documentation.
> remove references to pdc support

- docs/users.rst
Describe how the build args provided by the remote source plugins may be
used to extract and copy the remote sources into the build container.
* OSBS-8473
> Describe usage of remote source build args

- docs/users.rst
Emphasize that both fetch artifacts yaml files can be used for the same
build.
> Document fetch artifacts yaml files

- docs/build_process.rst
- docs/index.rst
- docs/users.rst
Documentation pinned to okd 3.11 as latest version changes
> Fix links to OKD docs

- docs/users.rst
The first commit rewrites the first paragraph in the "Override Parent Image" section to use the active voice so that users can understand it more easily.
The second commit clarifies that OSBS will only override the final "FROM" instruction for a multi-stage build.
Fixes: #118
> users: describe koji_parent_build for multi-stage builds

- docs/build_parameters.rst
* CLOUDBLD-397
Add to the example REACTOR_CONFIG, also add comments to explain the
difference between registries, source_registry and pull_registries.
> Document new pull_registries configmap option

- docs/users.rst
Explain the use-case, expected format, and ODCS behavior for the "modules" option. In particular, we almost always want OSBS users to consume modules from Pulp rather than cherry-picking builds that might or might not be tested or signed.
> users: explain "modules" use-case, format, and behavior

- docs/users.rst
Explain the main use-cases for setting "`ignore_absent_pulp_repos`" to "`true`" or "`false`".
> users: document use-cases for ignore_absent_pulp_repos

- docs/admins.rst
* CLOUDLD-397
Mention that allowed_registries for operator digest pinning should be
a subset of source_registry + pull_registries.
Documentation for users has no concept of supported/unsupported
registries, it should be fine to keep it that way.
> Document relation of pull_registries to operators

- docs/users.rst
> osbs doesn't forward "modular_koji_tags" to odcs

- docs/users.rst
Relates to CLOUDBLD-1598 and https://github.com/containerbuildsystem/atomic-reactor/pull/1511
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Add documentation for the Cachito packages parameter

- docs/users.rst
Debugging, running, pulling architectures which are not identical to the
host is possible with podman and docker!
Signed-off-by: arewm <arewm@users.noreply.github.com>
> Add information for debugging multi-arch builds

- docs/users.rst
Rephrase the sentence about Pulp repository IDs to use the active voice.
Show how users can use content set names or repository IDs with RHEL 7 and RHEL 8 examples that are easy to copy and paste.
> users: improve content set examples

- docs/users.rst
Hello, 
There are already many supported pkg managers in Cachito. 
Maybe it worth to add a mention about the pkg manager part into the Cachito docs.
> Add link to Cachito pkg managers doc

- docs/users.rst
All artifacts fetched via fetch-artifacts-koji will now be included
in brew image metadata
MMENG-1275
> add documentation for metadata updates for fetch-artifacts-koji metadata

- docs/users.rst
`add_timestamp_to_release` works only with hardcoded release in the
Dockerfile
> Autorebuilds: clarify that release must be specified

- docs/.aspell.en.pws
- docs/build_parameters.rst
- docs/users.rst
Pulp registry is unsupported for long time already
> Remove traces of Pulp image registry

- docs/users.rst
In [Base image builds](https://osbs.readthedocs.io/en/latest/users.html#odcs-compose), there is a parameter typo. This PR replaces `repo=url` with `repo-url` in the code example.
> Fix repo=url parameter typo

- .github/workflows/linters.yaml
- docs/admins.rst
- docs/build_process.rst
- docs/index.rst
- docs/users.rst
✅ [Test run][] in my fork
Note that there *are still* linter hits:
docs/admins.rst:322: D000 Unknown target name: "config.json".
docs/admins.rst:350: D000 Unknown target name: "config.json".
docs/admins.rst:430: D000 Unknown target name: "config.json".
I don't know the intent there, so I don't know how to fix them.
Signed-off-by: Ben Alkov <ben.alkov@redhat.com>
[Test run]: https://github.com/ben-alkov/osbs-docs/runs/4121040810?check_suite_focus=true
> Add GitHub workflow for doc8

- docs/admins.rst
CLOUDBLD-8889
The file is now generated from Tekton results instead, and it is no
longer possible to configure the included annotations via a whitelist.
The task_annotations_whitelist configuration option referenced in the
removed content is not present anywhere else in the docs.
Remove the mention of the remote_source_url annotation entirely, it has
no meaning in the admins doc outside of the whitelisting context. Not to
mention that this annotation is outdated (replaced by remote_sources).
> Document changes to build_annotations.json

- docs/users.rst
Label group_manifests was defined in the Orchestrator section, which has
been removed during development of OSBS 2. This change is helpful to
make the `make html' succeed completely in local to generate complete
static site content.
> Remove reference to undefined label group_manifests

- docs/users.rst
CLOUDBLD-8399
Signed-off-by: Sumin Cho <sucho@redhat.com>
Reference to Issue #163:
> We should update the documentation to steer users away from using the go key in container.yaml. This is the old deprecated way of performing container-first builds in OSBS. Cachito is the replacement. To switch to Cachito, set the remote_source key instead. OSBS does not permit users to specify a go key with a remote_source key.
I have added this information to the warning tag under "go" section.
> Document deprecated "go" settings

- docs/admins.rst
- docs/users.rst
CLOUDBLD-6771
Since using multiple remote sources in cachito is
preferred and because we intend to deprecate the
single remote source option in the future, multiple
remote sources should be presented as the only option
Signed-off-by: Taylor Madore <tmadore@redhat.com>
> undocument cachito single remote source

- docs/users.rst
I came across this issue when trying to use a tag that contains a `-` in an OpenShift Build Service (OSBS) build for 3scale API Management.
> Document valid pattern for floating tags

- docs/users.rst
Clarify that a `compose` section simply makes the `.repo` file available in the build environment. It does not install any packages into the image.
> users: clarify "compose" section operation
