containerbuildsystem/osbs-docs

- docs/conf.py
- docs/design.rst
- docs/images/after-build.dot
- docs/images/during-build.dot
- docs/index.rst
- docs/multiarch.rst
This pull request adds a section describing the design for multi-platform container image builds.
@csom, @lcarva
> Multiarch design

- docs/multiarch.rst
> Only allow --arches for scratch builds

- docs/multiarch.rst
> multiarch: new plugins for worker metadata

- docs/multiarch.rst
> Add more specifics about koji_upload

- docs/multiarch.rst
> Describe changes required for logging

- docs/contributors.rst
> Add policy about handling errors with retries

- docs/multiarch.rst
> Clarify --arches documentation

- docs/multiarch.rst
This reverts commit 96ea61be3f42a8eed1bc251d6418c91f67c381f3.
> Restore compare_rpm_packages: needed after all

- docs/users.rst
> Describe arrangement version 2

- docs/multiarch.rst
> Improve formatting

- docs/multiarch.rst
> Describe koji_upload_dir parameter for create_worker_build

- docs/multiarch.rst
> Describe delete_from_registry changes

- docs/multiarch.rst
> Describe worker build 'help' annotation

- docs/multiarch.rst
> Use set intersection for platforms.only

- docs/multiarch.rst
> Don't run certain plugins for scratch builds

- docs/users.rst
> Document the runPolicy we use

- docs/multiarch.rst
> Multi-platform tagging details

- docs/multiarch.rst
> describe group_manifests goarch parameter

- docs/users.rst
Also include more detail about arrangement version 2
> Describe arrangement version 3

- docs/multiarch.rst
> Describe new pulp_tag plugin, required for tagging API v1 images

- docs/multiarch.rst
> Describe pulp_push 'publish' parameter

- docs/multiarch.rst
> New publish parameter for pulp_sync as well

- docs/multiarch.rst
> Make it clear platform defs are needed everywhere

- docs/multiarch.rst
> rename compare_rpm_packages to compare_components

- docs/images/arrangement-v4.dot
- docs/users.rst
> Describe arrangement v4

- docs/multiarch.rst
> Update metadata description for v2 schema 2

- docs/design.rst
- docs/odcs.rst
> Add design for ODCS integration

- docs/odcs.rst
> odcs: clarify constraint of compose_ids API param

- docs/odcs.rst
> odcs: modify reactor-config odcs data structure

- docs/users.rst
> Describe new arrangement 5

- docs/build_parameters.rst
- docs/design.rst
> Describe lazy plugin rendering method

- docs/build_parameters.rst
> Fix typo in filename

- docs/contributors.rst
> Update PR review checklist (OSBS-5770)

- docs/build_process.rst
- docs/users.rst
While going through the docs, I found these minor typos. Here are my change suggestions.
> Fix typos found during docs proofreading

- docs/admins.rst
> Describe atomic-reactor SIGUSR1 handling feature

- docs/users.rst
Describe the new behavior with an empty packages section.
> empty packages behavior

- docs/users.rst
Use a "-container" suffix in the example component name.
> users: use -container suffix

- docs/build_process.rst
- docs/users.rst
> Add operator manifests extraction information

- docs/users.rst
> inherit yum repositories and odcs composes from baseimage build

- docs/contributors.rst
> Mention test.sh in contributors.rst

- docs/build_process.rst
> Mention that versions < 6 are no longer supported

- docs/admins.rst
- docs/build_parameters.rst
- docs/build_process.rst
> Remove references to v1 content pushes to Pulp

- docs/admins.rst
- docs/users.rst
> Describe operators koji BType creation

- docs/build_parameters.rst
Signed-off-by: Clement Verna <cverna@tutanota.com>
> Update the configmap example with Koji's fast upload option

- docs/admins.rst
> Describe build_from more fully

- docs/users.rst
> Describe how floating tags are chosen

- docs/users.rst
> Describe automatically generated labels

- docs/admins.rst
- docs/users.rst
> OMPS integration

- docs/users.rst
> Update info about operators manifests

- docs/users.rst
> Document deep manifest list inspections

- docs/users.rst
> Improve documentation for manifest digest checks

- docs/users.rst
> Update required labels requirements in dockerfile

- docs/users.rst
> Document missing entries for container.yaml

- docs/build_process.rst
- docs/users.rst
> add timestamp to explicitly specified release for autorebuilds

- docs/users.rst
Rewrite the "Image tags" section to describe the three categories of tags that OSBS uses: "unique", "primary", and "floating".
Drop the first paragraph from the "Isolated Builds" section since it duplicates the Image tags section above. Use the term "floating tags" here instead. This should hint to the user to scroll up and read about what a "floating tag" is.
Update the final paragraph in the "Isolated Builds" section so that our definitions of "primary tag" and "unique tag" match what the "Image tags" section.
> users: describe "unique", "primary", and "floating" tags

- docs/build_process.rst
- docs/conf.py
- docs/index.rst
- docs/reference_docs.rst
- docs/users.rst
This was fixed using sphinx's linkcheck builder
> Fix Broken URLs

- docs/images/osbs-structure.svg
- docs/index.rst
This picture shows how the OSBS components fit together.
> add OSBS structure diagram to index page

- docs/build_process.rst
- docs/images/arrangement-v6.dot
> Add a pulp-less diagram for v6

- .travis.yml
> Add initial travis CI setup

- .travis.yml
> Install graphviz dep for Travis-CI

- docs/users.rst
> set_release_env: add documentation for set_release_env

- docs/users.rst
> Introduce source containers

- docs/admins.rst
> Document build annotations for Koji task output

- docs/admins.rst
- docs/users.rst
> Document cachito integration

- docs/users.rst
> Document cachito downloaded project root location

- docs/contributors.rst
> Add OSBS-Box content to contributors doc

- docs/users.rst
> make source containers aware of cachito

- docs/users.rst
> Add reference to content_sets.yml schema

- docs/users.rst
See https://github.com/containerbuildsystem/atomic-reactor/pull/1370
> Document setting flatpak base_image in container.yaml

- docs/users.rst
> Document cachito dependency replacement option

- docs/users.rst
> Document required golang version for cachito usage

- docs/users.rst
> base image will use also yum repos from composes

- docs/users.rst
> Prevent building source containers if lookaside is involved

- docs/admins.rst
- docs/users.rst
* CLOUDBLD-379
Create new top-level section in admins doc, move content related to
operator manifests there
admins: Document how to configure atomic-reactor for operator manifest
bundle builds
users: Document how to set up and what to expect from OSBS for operator
manifest bundle builds
>  Document operator manifest bundle builds

- docs/admins.rst
> Document signing intent keys deprecation process

- docs/users.rst
> Image owners can make ODCS ignore missing content sets

- docs/users.rst
* CLOUDBLD-493
pin_operator_digest plugin now also creates .spec.relatedImages after
replacing pullspecs in CSV files
If CSV file already has a relatedImages section, it is skipped.
> users: operator bundle builds and relatedImages

- docs/users.rst
> Embed content sets information in built container images

- docs/users.rst
> Option to allow OSBS autorebuilds to ignore isolated parent builds

- docs/users.rst
> Move content sets data to content manifest file

- docs/users.rst
> operators: Document heuristic annotation pullspecs

- docs/users.rst
> fixup: Heuristic pullspecs documentation

- docs/users.rst
> Update Digests verification section

- docs/admins.rst
- docs/build_parameters.rst
* CLOUDBLD-1228
Add example to REACTOR_CONFIG and a short explanation to the admins doc.
> Document build_env_vars configmap option

- docs/admins.rst
> Add doc of limiting image size

- docs/users.rst
> Update cachito pkg_managers configuration behavior

- docs/users.rst
> Document Image Content Manifests creation

- docs/users.rst
> Build only content sets used just for building content

- docs/users.rst
> Document go container.yaml key deprecation

- docs/admins.rst
- docs/users.rst
> Feature to allow bypassing all OSBS operator processing

- docs/users.rst
> Allow specifying repo id in content_sets.yml

- docs/users.rst
Closes CLOUDBLD-3475
Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>
> Set env variables with cachito.env script

- docs/users.rst
Closes CLOUDBLD-3475
Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>
> Add an alias for cachito.env file path

- docs/contributors.rst
> Update usage of Travis CI to GitHub Actions

- docs/users.rst
Tell Sphinx to syntax-highlight these examples as YAML.
> users: syntax highlighting for more YAML examples

- docs/admins.rst
- docs/users.rst
Documentation for Operator CSV modifications for isolated builds
Updated both user and admin documentation.
CLOUDBLD-3976
> Operator CSV modifications

- docs/admins.rst
> Allow setting custom self-signed cert for ODCS

- docs/users.rst
add documentation for metadata updates for fetch-artifacts-koji metadata
Epic MMENG-829
MMENG-1274
> update fetch-artifacts-url shcema and metadata documentation

- docs/users.rst
> add documentation for fetch-artifacts-pnc

- docs/admins.rst
- docs/users.rst
Signed-off-by: mkosiarc <mkosiarc@redhat.com>
> Add info about remote sources

- docs/users.rst
Signed-off-by: mkosiarc <mkosiarc@redhat.com>
> Update remote sources docs

- docs/users.rst
Simplify and clarify this section.
> users: rewrite Koji Build Metadata Integration section

- docs/users.rst
> PNC ids are string now

- docs/users.rst
new changes from MMENG-1925 will add additional data to
the ICM
MMENG-1925
> update ICM documentation

- docs/admins.rst
> Add osbs.conf example for osbs2

- .readthedocs.yaml
- docs/requirements.txt
This will prevent random build failures due updates of dependencies
> Make reproducible builds

- .readthedocs.yaml
- docs/requirements.txt
This will prevent random build failures due updates of dependencies
> [OCP3] Make reproducible builds

- docs/build_parameters.rst
- docs/users.rst
> Remove autorebuilds

- docs/build_parameters.rst
> clarify we only accept one registry to push the results to

- docs/build_process.rst
> document changes to OSBS log retrieval API

- docs/admins.rst
Remove deprecated cluster section from documentation
CLOUDBLD-8995
Signed-off-by: Ladislav Kolacek <lkolacek@redhat.com>
> Document configmap section for remote-hosts

- docs/users.rst
Also remove outdated section about setting other automatic labels
> Drop build-host label

- docs/admins.rst
Documentation about supported template variables by osbs-client
CLOUDBLD-9475
> PipelineRun template variables

- docs/build_parameters.rst
> remove all traces of clusters configuration

- docs/admins.rst
> document `cleanup_used_resources` configuration

- docs/build_parameters.rst
> Update reactor config map example with new registries_cfg_path config

- docs/build_process.rst
CLOUDBLD-9876
Signed-off-by: mkosiarc <mkosiarc@redhat.com>
> Link the Tekton task definitions

- docs/index.rst
> Update version warning

- .github/workflows/linters.yaml
Older versions run with unsupported nodejs
> workflow: use checkout action version 3

- docs/admins.rst
- docs/users.rst
> add documentation for configurable build time

- docs/build_process.rst
> add documantion about icm

- docs/users.rst
> FROM scratch will fail when koji_parent_build is provided

- docs/admins.rst
- docs/users.rst
Hermeto is another method for remote sources
> Add Hermeto
